### ISSUE TITLE
can not execute sh fifo_zlogin_latest

### ISSUE THREAD

**Issue by TonyBostonTB** [project-fifo/fifo-zlogin#1]
[root@storage01 /opt]# sh fifo_zlogin-latest 
cp: cannot access /opt/fifo_zlogin/share/epmd.xml
svccfg: Unable to stat file /opt/custom/smf/epmd.xml.  No such file or directory

What else do you need to dig into it? I used the official install notes.

**Comment by Licenser** [comment]
see: https://gitlab.com/Project-FiFo/FiFo/fifo-zlogin/issues/3
